# Основные настройки numpy

При работе с библиотекой numpy, важно знать и уметь настраивать их основные параметры. Это может повысить эффективность и удобство работы с библиотекой.

#Numpy - это библитоека для работы с многомерными массивами и  матрицами. 
Основные настройки numpy:
1. np.set_printoptions(precision=n) - определяет количество знаков после запятой при вводе массивов numpy.
2. np.set_printoptions(suppress=True) - отключает вывод научной нотации при выводу массивов numpy.
3. np.seterr(all='ignore') - игнорирует  все ошибки при выполнении операций с массивами numpy.


# СПОСОБЫ   СОЗДАНИЯ ОДНОМЕРНЫХ МАССИВОВ

In [11]:
#Первый   способ
import numpy as np
np.set_printoptions(precision=5)
my_list = [1,2,3,4,5]
my_array = np.array(my_list)
my_array1 = np.array(range(5))
print(my_array)
print(my_array1)


[1 2 3 4 5]
[0 1 2 3 4]


In [38]:
#Второй способ - это создание массива с помощью функции zeros, rand и т.п.
zeros_array = np.zeros((5,3))
ones_array = np.ones((4,2))
random_array = np.random.rand(2) # функция np.random.zeros создает массив со значениями от 0 до 1;
print(zeros_array)
print(ones_array)
print(random_array)
print(np.empty(10, dtype=int))
#Наконец в numpy есть функция full(), которая создает массив заданной формы, заполненный заданным значением.
#Синтаксис функции для одномерного использования:
#np.full(shape, fill_value, dtype=None)
print(np.full((2,3),5))

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]
[0.99775 0.25487]
[4603581549134298145 4603231609662883391 4602022093595458108
 4594099269384025312 4604994370357329256 4590874646936298408
 4604722327278109226 4589112179967260208 4603271365097599382
 4597131996734260784]
[[5 5 5]
 [5 5 5]]


In [25]:
#Третий способ - это создание массивов с помощью функции arange() and linspace()
print(np.arange(1,6))
print(np.linspace(1,5,5))
# np.arange() создает содержащий последовательность символов от n до n включительно
# np.linspace() создает содержащий последовательность символов от n до n включительно разделенное на определенное
#количество равных промежутков

[1 2 3 4 5]
[1. 2. 3. 4. 5.]


In [ ]:
#Четвертый способ - создание с помощтю ввода пользователя 
user_input = input('Введите несколько чисел разделенных пробелом: ')
user_array = np.array(user_input.split(), dtype=float)
print(user_array)

#также   массив  можно создать  при   помощи  функции fromstring
#numpy.fromstring(string, dtype=float, count=-1, sep='')
# Параметры
# - string: входная строка, представляющая элементы массива.
# - dtype: тип данных элементов массива. По умолчанию равен float.
# - count: количество элементов, которые следует считать. 
# Если указать -1 (по умолчанию), будут считаны все элементы.
# - sep: разделитель между элементами. 
# Если разделитель не указан или равен пустой строке (по умолчанию), строка должна быть закодирована в двоичном формате. 
# Если разделитель указан, строка будет разделена данным разделителем.
data = '1,2,3,4,5'
arr = np.fromstring(data, dtype=np.int32, sep=',')
print(arr)

In [ ]:
#Пятый способ - создание новых ассивов по форме других массивов
a =  np.array([1,2,3,4])
b = np.zeros_like(a)
print(b)

Создайте одномерный numpy массив чисел от 0 до 9 и выведите его на экран. Не забудьте импортировать библиотеку.

In [39]:
import numpy as  np
print(np.arange(10))

[0 1 2 3 4 5 6 7 8 9]


Создайте массив из первых 10 нечетных чисел и выведите его на экран.


In [41]:
import numpy as np
print(np.array([i for i in range(1,20) if i % 2 != 0]))
print(np.arange(1,20,2))

[ 1  3  5  7  9 11 13 15 17 19]
[ 1  3  5  7  9 11 13 15 17 19]


Создайте массив numpy, содержащий числа от 1 до 10, включительно, с шагом 0.5, выведите его на экран.


In [43]:
import numpy  as np
print(np.arange(1,10.5,0.5))

[ 1.   1.5  2.   2.5  3.   3.5  4.   4.5  5.   5.5  6.   6.5  7.   7.5
  8.   8.5  9.   9.5 10. ]


Создайте массив, содержащий 10 равноудаленных элементов в интервале от -5 до 5

In [45]:
import numpy  as  np
print(np.linspace(-5,5,10))

[-5.      -3.88889 -2.77778 -1.66667 -0.55556  0.55556  1.66667  2.77778
  3.88889  5.     ]


Создайте массив, содержащий числа от 10 до 1 в обратном порядке.

In [46]:
import numpy as np
print(np.arange(10,0,-1))

[10  9  8  7  6  5  4  3  2  1]


На вход подаются 2 числа a и b в виде строки чисел через пробел. Создайте массив NumPy, содержащий числа от a до b включительно, кратные 3, выведите его на экран

In [47]:
import numpy as  np
start,stop  = map(int, input().split())
print(np.array([i for i in range(start,stop+1) if i % 3 == 0]))

 0 3


[0 3]


На вход подается целое число n. Cоздайте массив из n случайных действительных чисел в интервале от 0 до 1 не включительно.

In [48]:
import numpy as np
np.random.seed(32)
print(np.random.rand(int(input())))

 10


[0.85889 0.37271 0.55513 0.95566 0.73667 0.81621 0.10109 0.92849 0.60911
 0.59655]


In [ ]:
%lsmagic